[ananke]
show_recent_posts = true # show recent posts on the homepage

[ananke.social]
icon_path = "ananke/socials/%s.svg"

[ananke.social.follow]
new_window_icon = false # show a little "opens in new window" icon next to the link
# add networks to this list in your local config to enable them, remove them to disable them.
 networks = [
   "home",
   "search",
   "contact",
   "github",
   "youtube",
   "bluesky",
   "mastodon"
 ]

[ananke.social.share]
icons = true # show icons for each share link
sharetext = true # show the share text
# add networks to this list in your local config to enable them, remove them to disable them.
 networks = [
   "bluesky",
   "mastodon",
]

[ananke.social.bluesky]
username = "CarryOnRTW"

[ananke.social.youtube]
username = "CarryOnRTW"

[ananke.social.mastodon]
username = "CarryOnRTW"

[ananke.social.github]
username = "RoninTech"

# social media network setups
[ananke.social.networks.bluesky]
slug = "bluesky"
label = "Bluesky"
color = "#1185fe"
profile = "https://bsky.app/profile/%s.bsky.social"
icon = "bluesky" # font awesome brand icon name
link = "https://bsky.app/intent/compose"
[ananke.social.networks.bluesky.particles]
text = "permalink"

[ananke.social.networks.github]
slug = "github"
label = "GitHub"
color = "#6cc644"
profile = "https://github.com/%s/"
icon = "github" # font awesome brand icon name

[ananke.social.networks.mastodon]
slug = "mastodon"
label = "Mastodon"
color = "#6364FF"
profile = "https://mastodon.social/@%s"
icon = "mastodon" # font awesome brand icon name
link = "https://mastodon.social/?text="
[ananke.social.networks.mastodon.particles]
text = "permalink"

[ananke.social.networks.youtube]
slug = "youtube"
label = "YouTube"
color = "#cd201f"
username = "CarryOnRTW"
profile = "https://www.youtube.com/@%s"
icon = "youtube" # font awesome brand icon name

[ananke.social.networks.contact]
slug = "contact"
label = "Contact"
color = "#ffa500"
icon = "contact"
profile = "/contact/"

[ananke.social.networks.search]
slug = "search"
label = "Search"
color = "#ffff00"
icon = "search"
profile = "/search/"

[ananke.social.networks.home]
slug = "home"
label = "Home"
color = "#0000ff"
icon = "home"
profile = "/"

