baseURL = "https://carryonrtw.com"
languageCode = "en-us"
title = "Carry On Round The World"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-QT3G9GJDXC"
enableRobotsTXT = true
enableEmoji = true

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/CarryOnRTW"
#[[params.ananke_socials]]
#name = "facebook"
#url = "https://facebook.com/CarryOnRTW"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/RoninTech"
#[[params.ananke_socials]]
#name = "linkedin"
#url = "https://www.linkedin.com/in/paul-rimmer-a46a461/"
[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@CarryOnRTW"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.renderer]
  unsafe= true

[params]
  favicon = "/images/favicons.png"
  site_logo = "/images/cropped-rtw_icon-150x150.png"
  description = "Carry On luggage only travels and adventures around the world with Canadians Paul and Helen Rimmer"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  post_content_classes = "arial"
  featured_image = "https://lh3.googleusercontent.com/pw/ACtC-3cIHwloNWDNzbmrs9zjP1IMY3dTwjcBK-nlazzyG-p55SgqrripkjmG0pqahMbGWXvX5KPVMDlCCaCsoLqzrcEuTBqehgwAtH_YrjvLwlIojUtyiTjYeog5Q_eyaQphKJ3BE9V7zRR1NnDDvWTEdrbErg=w1920-h670-no"
  recent_posts_number = 5
  show_reading_time = true
  commentoEnable = false
  mainSections = ["travels", "van-life", "articles", "packs"]
  custom_css = ["formatted_tables.css", "next_prev_links.css", "site_search.css"]

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Travels"
    identifier = "travels"
    url = "/travels/"
    weight = 2

  [[menu.main]]
    name = "Van Life"
    identifier = "van-life"
    url = "/van-life/"
    weight = 3

  [[menu.main]]
    name = "Packs"
    identifier = "packs"
    url = "/packs/"
    weight = 5

  [[menu.main]]
    name = "Articles"
    identifier = "articles"
    url = "/articles/"
    weight = 4

  [[menu.main]]
    name = "About Us"
    identifier = "about"
    url = "/about/"
    weight = 6

  [[menu.main]]
    name = "Search"
    identifier = "search"
    url = "/search/"
    weight = 7 

[module]
[[module.imports]]
    path = 'github.com/theNewDynamic/gohugo-theme-ananke'
    disable = false
